__INSTALL_DIR__/logs/*.log {
    daily
    rotate 14
    compress
    missingok
    notifempty
    nocreate
}
__LOG_DIR__/dlg_stats.log __LOG_DIR__/infra_alert.log {
    daily
    rotate 3
    compress
    missingok
    notifempty
    nocreate
}
